### ISSUE TITLE
我要坠吼的功能！

### ISSUE THREAD

**Issue by GaiZhenbiao** [Keldos-Li/Kelpy-Codos#1]
### 相关问题

我寻思也妹有问题啊

### 可能的解决办法

俺咋知道啊？

### 帮助开发

- [ ] 我愿意帮忙帮助开发！

### 补充说明

<img width="609" alt="image" src="https://user-images.githubusercontent.com/51039745/227725044-0919915b-d3b2-4571-b2f8-c3cff273930a.png">

**Comment by Keldos-Li** [comment]
哈哈哈哈哈
